tap "charmbracelet/tap"
tap "jetbrains/utils"
tap "probe-rs/probe-rs"

brew "ansible"
brew "ansible-language-server"
brew "ansible-lint"
brew "autopep8"
brew "aws-cdk"
brew "awscli"
brew "bash"
brew "bash-language-server"
brew "buf"
brew "ccls"
brew "cmake"
brew "codebook-lsp"
brew "charmbracelet/tap/crush"
brew "ctags"
brew "dart-sdk"
brew "delve"
brew "emmylua_ls"
brew "fish"
brew "fish-lsp"
brew "flake8"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "go"
brew "gopls"
brew "gradle"
brew "gradle-completion"
brew "haskell-language-server"
brew "haskell-stack"
brew "htop"
brew "jq"
brew "jetbrains/utils/kotlin-lsp"
brew "kube-ps1"
brew "kubernetes-cli"
brew "libgit2"
brew "llvm"
brew "luarocks"
brew "mas"
brew "metals"
brew "neovim"
brew "neovim-remote"
brew "node"
brew "openjdk"
brew "openjdk@17"
brew "openjdk@21"
brew "probe-rs/probe-rs/probe-rs"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python-lsp-server"
brew "python@3.13"
brew "revive"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "staticcheck"
brew "stern"
brew "stylua"
brew "subversion"
brew "tree-sitter-cli"
brew "typescript"
brew "typescript-language-server"
brew "watch"
brew "wget"
brew "yaml-language-server"
brew "zoxide"

cask "aerial"
cask "brooklyn"
cask "coconutbattery"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "github"
cask "hammerspoon"
cask "kitty"
cask "monitorcontrol"
cask "signal"
cask "slack"
cask "telegram"
cask "visual-studio-code"

mas "Ghostery Lite", id: 6504861501
mas "Pixelmator Pro", id: 1289583905
mas "Wipr", id: 1662217862
mas "StatusClock", id: 552792489
mas "Pages", id: 409201541
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825

vscode "vscodevim.vim"
vscode "hbenl.vscode-test-explorer-liveshare"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "LittleFoxTeam.vscode-python-test-adapter"
vscode "golang.go"
vscode "fwcd.kotlin"
vscode "rust-lang.rust-analyzer"
vscode "swellaby.vscode-rust-test-adapter"
vscode "scalameta.metals"
