
[homebrew]
taps = [
  "homebrew/cask-fonts",
]
bottles = [
  "aerial",
  "awscli",
  "brooklyn",
  "ctags",
  "cmake",
  "colordiff",
  "ddate",
  "font-fira-code",
  "font-meslo-for-powerline",
  "font-source-code-pro-for-powerline",
  "fzf",
  "github",
  "go",
  "gopls",
  "gradle",
  "htop",
  "iterm2",
  "mas",
  "openjdk@11",
  "postman",
  "kubernetes-cli",
  "kube-ps1",
  "libgit2",
  "neovim",
  "node",
  "python@3.9",
  "pyenv",
  "pyenv-virtualenv",
  "r",
  "ripgrep",
  "scroll-reverser",
  "shellcheck",
  "signal",
  "slack",
  "spotify",
  "subversion",
  "telegram",
  "visual-studio-code",
  "watch",
  "zsh",
  "docker",
]

[python]
packages = [
  "autopep8",
  "pylint",
  "flake8",
  "rope",
  "mccabe",
  "pyflakes",
  "jedi",
  "pynvim",
  "mypy",
  "pyls-black",
  "python-language-server",
  "virtualenvwrapper",
]

[vscode]
extensions = [
  "ms-python.python",
  "vscodevim.vim",
  "golang.go",
  "arcticicestudio.nord-visual-studio-code",
  "ms-azuretools.vscode-docker",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "fwcd.kotlin",
]

[npm]
packages = [
  "dockerfile-language-server-nodejs",
  "bash-language-server",
  "vim-language-server",
]

[go]
modules = [
  { exe = "cobra", path = "github.com/spf13/cobra/cobra"},
  { exe = "staticcheck", path = "honnef.co/go/tools/cmd/staticcheck"},
  { exe = "gorelease", path = "golang.org/x/exp/cmd/gorelease"},
]

[symlink]
links = [
  { sourceFile ="${HOME}/dotfiles/nvim/", linkName="${HOME}/.config/nvim" },
  { sourceFile ="${HOME}/dotfiles/gitconfig", linkName="${HOME}/.gitconfig" },
  { sourceFile ="${HOME}/dotfiles/gitignore_globa", linkName="${HOME}/.gitignore_global" },
  { sourceFile ="${HOME}/dotfiles/stCommitMsg", linkName="${HOME}/.stCommitMsg" },
  { sourceFile ="${HOME}/dotfiles/iterm2", linkName="${HOME}/.iterm2" },
  { sourceFile ="${HOME}/dotfiles/zshrc", linkName="${HOME}/.zshrc" },
  { sourceFile ="${HOME}/dotfiles/prezto", linkName="${HOME}/.zprezto" },
  { sourceFile ="${HOME}/dotfiles/zpreztorc", linkName="${HOME}/.zpreztorc" },
  { sourceFile ="${HOME}/dotfiles/zshenv", linkName="${HOME}/.zshenv" },
  { sourceFile ="${HOME}/dotfiles/zprofile", linkName="${HOME}/.zprofile" },
  { sourceFile ="${HOME}/dotfiles/zsh", linkName="${HOME}/.zsh" },
  { sourceFile ="${HOME}/dotfiles/R/RProfile", linkName="${HOME}/.RProfile" },
  { sourceFile ="${HOME}/dotfiles/vscode/settings.json", linkName="${HOME}/Library/Application Support/Code/User/settings.json" },
]
