
[homebrew]
taps = [
  "charmbracelet/tap/",
  "JetBrains/utils/",
]
bottles = [
  "aerial",
  "ansible",
  "ansible-language-server",
  "ansible-lint",
  "antidote",
  "autopep8",
  "aws-cdk",
  "awscli",
  "bash",
  "bash-language-server",
  "brooklyn",
  "buf",
  "ccls",
  "cmake",
  "coconutbattery",
  "codebook-lsp",
  "colordiff",
  "crush",
  "ctags",
  "dart-sdk",
  "delve",
  "firefox",
  "fish",
  "fish-lsp",
  "flake8",
  "font-fira-code-nerd-font",
  "font-meslo-for-powerline",
  "font-source-code-pro-for-powerline",
  "fzf",
  "gh",
  "git",
  "git-delta",
  "git-lfs",
  "github",
  "go",
  "gopls",
  "gradle",
  "gradle-completion",
  "hammerspoon",
  "haskell-language-server",
  "haskell-stack",
  "htop",
  "iterm2",
  "jq",
  "julia",
  "kitty",
  "kotlin-lsp",
  "kube-ps1",
  "kubernetes-cli",
  "libgit2",
  "llvm",
  "lua-language-server",
  "luarocks",
  "mas",
  "metals",
  "monitorcontrol",
  "neovim",
  "neovim-remote",
  "node",
  "openjdk",
  "openjdk@17",
  "openjdk@21",
  "podman",
  "pyenv",
  "pyenv-virtualenv",
  "python-lsp-server",
  "python@3.13",
  "r",
  "revive",
  "ripgrep",
  "rust-analyzer",
  "rustup",
  "shellcheck",
  "shfmt",
  "signal",
  "slack",
  "starship",
  "staticcheck",
  "stern",
  "stylua",
  "subversion",
  "telegram",
  "typescript",
  "typescript-language-server",
  "visual-studio-code",
  "watch",
  "wget",
  "yaml-language-server",
  "zoxide",
  "zplug",
  "zsh",
]

[julia]
modules =[
  "LanguageServer",
  "Pluto"
]

[vscode]
extensions = [
  # general purpose
  "vscodevim.vim",
  "hbenl.vscode-test-explorer-liveshare",
  "arcticicestudio.nord-visual-studio-code",
  "mhutchie.git-graph",
  # tools
  "ms-azuretools.vscode-docker",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "ms-vscode-remote.remote-containers",
  # languages
  "ms-python.python",
  "ms-python.vscode-pylance",
  "LittleFoxTeam.vscode-python-test-adapter",
  "golang.go",
  "fwcd.kotlin",
  "rust-lang.rust-analyzer",
  "swellaby.vscode-rust-test-adapter",
  "scalameta.metals",
]

[npm]
packages = [
  "vim-language-server",
  "@anthropic-ai/claude-code",
]

[go]
modules = [
  { exe = "jsonnet-language-server", path = "github.com/grafana/jsonnet-language-server"},
  { exe = "docker-language-server", path = "github.com/docker/docker-language-server/cmd/docker-language-server"},
]

[mac]
profile = "jansteinke@icloud.com"
apps = [
  { name="Ecosia", id="1463400445" },
  { name="Ghostery Lite", id="6504861501" },
  { name="Pixelmator Pro", id="1289583905" },
  { name="Wipr", id="1320666476" },
]
preferences = [
  { name="NSGlobalDomain.KeyRepeat", type="int", value="1" },
  { name="NSGlobalDomain.InitialKeyRepeat", type="int", value="20" },

  { name="com.apple.dock.minimize-to-application", type="int", value="1" },
  { name="com.apple.dock.show-process-indicators", type="int", value="1" },
  { name="com.apple.dock.mru-spaces", type="int", value="0" },
  { name="com.apple.dock.show-recents", type="int", value="0" },
  { name="com.apple.dock.tilesize", type="int", value="36" },

  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerTapGesture", type="int", value="2"},
  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerHorizSwipeGesture", type="int", value="0"},
  { name="com.apple.AppleMultitouchTrackpad.Clicking", type="int", value="1"},
  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerDrag", type="int", value="1"},

  { name="com.googlecode.iterm2.plist.PrefsCustomFolder", type="string", value="${HOME}/.iterm2" },
  { name="com.googlecode.iterm2.plist.LoadPrefsFromCustomFolder", type="int", value="1" },

  { name="com.apple.ActivityMonitor.IconType", type="int", value="6" },
]

[symlink]
links = [
  { sourceFile ="${PWD}/fish", linkName="${HOME}/.config/fish" },
  { sourceFile ="${PWD}/ghostty", linkName="${HOME}/.config/ghostty" },
  { sourceFile ="${PWD}/nvim", linkName="${HOME}/.config/nvim" },
  { sourceFile ="${PWD}/kitty", linkName="${HOME}/.config/kitty" },
  { sourceFile ="${PWD}/git", linkName="${HOME}/.config/git" },
  { sourceFile ="${PWD}/iterm2", linkName="${HOME}/.iterm2" },
  { sourceFile ="${PWD}/zsh_config/zshrc", linkName="${HOME}/.zshrc" },
  { sourceFile ="${PWD}/zsh_config/zshenv", linkName="${HOME}/.zshenv" },
  { sourceFile ="${PWD}/zsh_config/zprofile", linkName="${HOME}/.zprofile" },
  { sourceFile ="${PWD}/zsh_config/zplugins", linkName="${HOME}/.zplugins" },
  { sourceFile ="${PWD}/zsh_config/p10k.zsh", linkName="${HOME}/.p10k.zsh" },
  { sourceFile ="${PWD}/zsh", linkName="${HOME}/.zsh" },
  { sourceFile ="${PWD}/R/RProfile", linkName="${HOME}/.RProfile" },
  { sourceFile ="${PWD}/vscode/settings.json", linkName="${HOME}/Library/Application Support/Code/User/settings.json" },
  { sourceFile ="${PWD}/hammerspoon/", linkName="${HOME}/.hammerspoon" },
  { sourceFile ="${PWD}/starship.toml", linkName="${HOME}/.config/starship.toml" },
]
