
[homebrew]
taps = [
  "homebrew/cask-fonts",
  "bufbuild/buf",
]
bottles = [
  "aerial",
  "awscli",
  "aws-cdk",
  "brooklyn",
  "buf",
  "ccls",
  "ctags",
  "cmake",
  "colordiff",
  "ddate",
  "delve",
  "firefox",
  "font-fira-code-nerd-font",
  "font-meslo-for-powerline",
  "font-source-code-pro-for-powerline",
  "fzf",
  "git",
  "git-lfs",
  "github",
  "go",
  "gopls",
  "gradle",
  "gradle-completion",
  "htop",
  "iterm2",
  "julia",
  "mas",
  "openjdk",
  "openjdk@11",
  "openjdk@8",
  "postman",
  "kitty",
  "kotlin-language-server",
  "kubernetes-cli",
  "kube-ps1",
  "libgit2",
  "llvm",
  "lua-language-server",
  "markdownlint-cli",
  "neovim",
  "node",
  "podman",
  "python",
  "pyenv",
  "pyenv-virtualenv",
  "r",
  "ripgrep",
  "rustup-init",
  "rust-analyzer",
  "shellcheck",
  "shfmt",
  "signal",
  "slack",
  "spotify",
  "stern",
  "stylua",
  "subversion",
  "telegram",
  "visual-studio-code",
  "watch",
  "wget",
  "zplug",
  "zsh",
]

[julia]
modules =[
  "LanguageServer",
  "Pluto"
]

[python]
packages = [
  "autopep8",
  "pylint",
  "flake8",
  "rope",
  "mccabe",
  "neovim-remote",
  "pyflakes",
  "jedi",
  "pynvim",
  "mypy",
  "pyls-black",
  "yapf",
  "python-lsp-server",
  "virtualenvwrapper",
]

[vscode]
extensions = [
  # general purpose
  "vscodevim.vim",
  "hbenl.vscode-test-explorer-liveshare",
  "arcticicestudio.nord-visual-studio-code",
  # tools
  "ms-azuretools.vscode-docker",
  "ms-kubernetes-tools.vscode-kubernetes-tools",
  "ms-vscode-remote.remote-containers",
  # languages
  "ms-python.python",
  "ms-python.vscode-pylance",
  "LittleFoxTeam.vscode-python-test-adapter",
  "golang.go",
  "ethan-reesor.vscode-go-test-adapter",
  "fwcd.kotlin",
  "matklad.rust-analyzer",
  "swellaby.vscode-rust-test-adapter",
  "scalameta.metals",
]

[npm]
packages = [
  "bash-language-server",
  "dockerfile-language-server-nodejs",
  "vim-language-server",
  "yaml-language-server",
  "typescript",
  "typescript-language-server",
]

[go]
modules = [
  { exe = "cobra", path = "github.com/spf13/cobra/cobra"},
  { exe = "staticcheck", path = "honnef.co/go/tools/cmd/staticcheck"},
  { exe = "gorelease", path = "golang.org/x/exp/cmd/gorelease"},
]

[mac]
profile = "jansteinke@icloud.com"
apps = [
  { name="Ecosia", id="1463400445" },
  { name="Ghostery Lite", id="1436953057" },
  { name="Pixelmator Pro", id="1289583905" },
  { name="Twitter", id="1482454543" },
  { name="Wipr", id="1320666476" },
]
preferences = [
  { name="NSGlobalDomain.KeyRepeat", type="int", value="1" },
  { name="NSGlobalDomain.InitialKeyRepeat", type="int", value="20" },

  { name="com.apple.dock.minimize-to-application", type="int", value="1" },
  { name="com.apple.dock.show-process-indicators", type="int", value="1" },
  { name="com.apple.dock.mru-spaces", type="int", value="0" },
  { name="com.apple.dock.show-recents", type="int", value="0" },
  { name="com.apple.dock.tilesize", type="int", value="36" },

  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerTapGesture", type="int", value="2"},
  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerHorizSwipeGesture", type="int", value="0"},
  { name="com.apple.AppleMultitouchTrackpad.Clicking", type="int", value="1"},
  { name="com.apple.AppleMultitouchTrackpad.TrackpadThreeFingerDrag", type="int", value="1"},

  { name="com.googlecode.iterm2.plist.PrefsCustomFolder", type="string", value="${HOME}/.iterm2" },
  { name="com.googlecode.iterm2.plist.LoadPrefsFromCustomFolder", type="int", value="1" },

  { name="com.apple.ActivityMonitor.IconType", type="int", value="6" },
]

[symlink]
links = [
  { sourceFile ="${HOME}/dotfiles/nvim", linkName="${HOME}/.config/nvim" },
  { sourceFile ="${HOME}/dotfiles/kitty", linkName="${HOME}/.config/kitty" },
  { sourceFile ="${HOME}/dotfiles/git/gitconfig", linkName="${HOME}/.gitconfig" },
  { sourceFile ="${HOME}/dotfiles/git/gitignore_global", linkName="${HOME}/.gitignore_global" },
  { sourceFile ="${HOME}/dotfiles/git/stCommitMsg", linkName="${HOME}/.stCommitMsg" },
  { sourceFile ="${HOME}/dotfiles/iterm2", linkName="${HOME}/.iterm2" },
  { sourceFile ="${HOME}/dotfiles/zsh_config/zshrc", linkName="${HOME}/.zshrc" },
  { sourceFile ="${HOME}/dotfiles/zsh_config/zshenv", linkName="${HOME}/.zshenv" },
  { sourceFile ="${HOME}/dotfiles/zsh_config/zprofile", linkName="${HOME}/.zprofile" },
  { sourceFile ="${HOME}/dotfiles/zsh_config/zplugins", linkName="${HOME}/.zplugins" },
  { sourceFile ="${HOME}/dotfiles/zsh_config/p10k.zsh", linkName="${HOME}/.p10k.zsh" },
  { sourceFile ="${HOME}/dotfiles/zsh", linkName="${HOME}/.zsh" },
  { sourceFile ="${HOME}/dotfiles/R/RProfile", linkName="${HOME}/.RProfile" },
  { sourceFile ="${HOME}/dotfiles/vscode/settings.json", linkName="${HOME}/Library/Application Support/Code/User/settings.json" },
]
