require("packages")
require("settings")

-- UI
require("ui.buffer_line")
require("ui.completion")
require("ui.diagnostics")
require("ui.extension")
require("ui.file_explorer")
require("ui.git")
require("ui.keymapprev")
require("ui.markdownprev")
require("ui.orgmode")
require("ui.scrollbar")
require("ui.status_line")
require("ui.syntax")
require("ui.telescope")
require("ui.terminal")
require("ui.test")
-- require("ui.theme")
require("ui.title")
require("ui.treesitter_context")
require("nord.theme")

-- LSP
require("lsp.dap")
require("lsp.packages")
