require("packages")
require("lsp")
require("treesitter")
require("file_explorer")
require("settings")
require("bufferline_config")
require("telescope_config")
require("dap_settings")
require("terminal")
require("vista")
require("git")

-- Language configs
require("languages.cpp")
require("languages.docker")
require("languages.go")
require("languages.kotlin")
require("languages.lua")
require("languages.misc")
require("languages.python")
require("languages.r")
require("languages.rust")
require("languages.scala")
require("languages.vim")
require("languages.yaml")

require("colorizer").setup()
