#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Jan Steinke <jan.steinke@gmail.com>
#
# Load Antigen configurations
source /usr/local/share/antigen/antigen.zsh
antigen init ~/.antigenrc

alias vim=nvim
alias diff=colordiff

# Environment Vars
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PATH=/usr/local/bin:$PATH

# Theme config
BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  dir
  kctx
  aws
  git
  go
  virtualenv
  cmd_exec_time
)
BULLETTRAIN_VIRTUALENV_FG=black
BULLETTRAIN_DIR_BG=magenta
BULLETTRAIN_AWS_BG=red
BULLETTRAIN_KCTX_BG=blue


# AWS
if [ -f ~/.aws/config ]; then
  export AWS_PROFILE=$(aws configure list-profiles 2>&1 | head -n 1)
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


# zsh-vi-mode compatibility for custom key-bindings
function zvm_after_init() {
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}

# Set the title bar in the shell
DISABLE_AUTO_TITLE="true"
function set_terminal_title() {
	if [[ $PWD == $HOME ]]
	then
		print -Pn "\e]2;~ (zsh)\a"
	else
		print -Pn "\e]2;$(basename $PWD) (zsh)\a"
	fi

}
add-zsh-hook precmd set_terminal_title
set_terminal_title
