#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Jan Steinke <jan.steinke@gmail.com>
#

# custom themes
fpath=(~/.zsh/custom_themes $fpath)
autoload -U promptinit && promptinit

setopt PROMPT_SUBST
# Theme config
BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  dir
  kctx
  aws
  git
  go
  virtualenv
  cmd_exec_time
)
BULLETTRAIN_VIRTUALENV_FG=black
BULLETTRAIN_DIR_BG=magenta
BULLETTRAIN_AWS_BG=red
BULLETTRAIN_KCTX_BG=blue

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# vim config
bindkey -v
bindkey '^r' history-incremental-search-backward
bindkey '^w' backward-kill-word

alias vim=nvim
alias diff=colordiff

# Environment Vars
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR=nvim
export VISUAL=nvim
export KEYTIMEOUT=1 # lag between switching vi modes
export PATH=/usr/local/bin:$PATH

# python configuration
if command -v pyenv > /dev/null 2>&1
then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
export WORKON_HOME=~/Envs

# Go configuration (installed with brew)
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Rust configuration
export CARGO_NET_GIT_FETCH_WITH_CLI=true

# completion
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i
source <(kubectl completion zsh)
unsetopt correct

# AWS
if [ -f ~/.aws/config ]; then
  export AWS_PROFILE=$(aws configure list-profiles 2>&1 | head -n 1)
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
