# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# remove / from wordchars to allow splitting on slash and backwards kill ^W to stop on /
WORDCHARS=${WORDCHARS/\/}

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Jan Steinke <jan.steinke@gmail.com>
#
# Load Antigen configurations
export ZPLUG_HOME=$(brew --prefix)/opt/zplug
source $ZPLUG_HOME/init.zsh

source ~/.zplugins

alias vim=nvim
alias diff=colordiff

# Environment Vars
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PATH=/usr/local/bin:$PATH

# AWS
if [ -f ~/.aws/config ]; then
	export AWS_PROFILE=$(aws configure list-profiles 2>&1 | head -n 1)
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


# zsh-vi-mode compatibility for custom key-bindings
function zvm_after_init() {
	[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}

# Set the title bar in the shell
DISABLE_AUTO_TITLE="true"
function set_terminal_title() {
	if [[ $PWD == $HOME ]]
	then
		print -Pn "\e]2;~ (zsh)\a"
	else
		print -Pn "\e]2;$(basename $PWD) (zsh)\a"
	fi

}
add-zsh-hook precmd set_terminal_title
set_terminal_title

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
