name: lua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.11.0
          args: --check $(find . -not -path "./submodules/*" -not -path "./nvim/plugin/*" -type f -name *.lua)

